name: Continuous Integration

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: "npm"

      - run: npm ci

      - name: Check types
        run: npm run typecheck

      - name: Check lint
        run: npm run lint --quiet

      - name: Run tests
        run: npm run test
