name: Continuous Integration

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: "npm"

      - run: npm ci

      - name: Check types
        run: npm run typecheck

      - name: Check lint
        run: npm run lint --quiet

      - name: Run tests
        run: npm run test
